---
slug: learn_enough_dev_environment
filename: learn_enough_dev_environment
title: Learn Enough Dev Environment to Be Dangerous
subtitle:
description: A tutorial introduction to computer development environments
author: Michael Hartl, Nick Merwin, and Lee Donahoe
copyright: 2017
uuid: 4345dc7b-6a04-4987-b247-31b88f7af068
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
